### ISSUE TITLE
Dependencies issue on isoparser

### ISSUE THREAD

**Issue by alexduros** [sannies/isoviewer#2]
I was unable to compile isoviewer with the provided isoparser dependency (relying on v1.0.5.3 from repo https://oss.sonatype.org/content/repositories/comgooglecodemp4parser-1049) 
Maybe, build from isoparser are juste temporarily broken.

By changing it with a default http://repo1.maven.org/maven2/ with version 1.0.5.4, it worked. 

Moreover, it would be great to tell non-Java developers (like me ;)) that Java8 is required to compile it since JavaFX is used (In fact, i was not able to do it with Java7 on exec without getting missing packages errors)

**Comment by sannies** [comment]
Hi Alex,
I do not publish all all releases to maven central - I only do so when people ask me to do cause I don't want to pollute a global, persistent repository with unused releases. All release are pushed to a staging repository from where I can either push it to central or just leave it there for some time. These staging repositories are cleared/dropped after some time and this is exactly the situation you ran into. 
I'll add the java 8 hint, java 7 also includes javafx but it is not in the default classpath. 
Thanks for taking the time and opening an issue!
Grüße,
Sebastian

**Comment by alexduros** [comment]
Hi Sebastian, 
And thank you for quick reply. That's clear for me! 
Why is this a problem to publish all releases (even unused) to maven central, since it would be representative of your github tags ? 
It just a curious question, since I am not a Java developer so I am not aware of maven publishing strategies.
Thank you!

**Comment by brendanlong** [comment]
This seems to be a problem with the 1.8 release too. I think you should push isoparser versions when doing an offical release, since right now they're not buildable..

**Comment by sannies** [comment]
I release very often and typically the releases are available on so called staging repositories on oss.sonatype.org - unfortunately sonatype is cleaning them up with an unknown interval. 
I could publish all of them but as maven central cannot shrink I'm hesitating to pollute central with too many versions.  If anyone needs a release I typically push it to central with a few days.
