### ISSUE TITLE
Can't run as a jar

### ISSUE THREAD

**Issue by brendanlong** [sannies/isoviewer#5]
When I download the latest release and try to run it, it says it can't find the main class:

    $ java -jar isoviewer-1.8.jar 
    Error: Could not find or load main class com.github.sannies.isoviewer.IsoViewerFx

I have no idea what's wrong since the jar file seems to be correct..

**Comment by sannies** [comment]
Hmm - I cannot reproduce that. When I download the Jar file then I can double-click the file and it starts. You might to try to start it from an IDE if you have a java IDE or build it with Maven on your own.

**Comment by brendanlong** [comment]
It might a Linux vs. Windows thing. You can close this if you want, since I don't have time to track down the issue if it's not reproducible for you.

**Comment by sannies** [comment]
It's now building. Sorry for the hassle.

**Comment by YongtaoS** [comment]
I also have the same problem with the versions from 1.8-2.0.2. Does anyone have a solution for that? Thank you!

```
$ java -jar isoviewer-1.11-SNAPSHOT.jar 
Error: Could not find or load main class com.github.sannies.isoviewer.IsoViewerFx

$ java -jar isoviewer-2.0.2-jfx.jar 
Error: Could not find or load main class ISOViewer
```
